### ISSUE TITLE
NOAA data

### ISSUE THREAD

**Issue by oscarbatori** [liquidata-inc/liquidata-etl-jobs#47]
ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily

**Comment by oscarbatori** [comment]
https://cloud.google.com/blog/products/data-analytics/weather-climate-big-data-from-noaa-now-in-cloud

Worth noting that Google are publishing this data so whatever we want to say about this we might want to highlight how our value proposition differs from Google.

**Comment by timsehn** [comment]
https://www.dolthub.com/repositories/Liquidata/noaa
